"""empty message

Revision ID: 487521075c2f
Revises: deaec5fb8fe5
Create Date: 2022-05-31 11:58:20.352473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487521075c2f'
down_revision = 'deaec5fb8fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
