"""empty message

Revision ID: deaec5fb8fe5
Revises: fda93089a261
Create Date: 2022-05-30 12:41:24.268082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaec5fb8fe5'
down_revision = 'fda93089a261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_pic', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pic')
    op.drop_column('post', 'post_pic')
    # ### end Alembic commands ###
